eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19041/eureka/

server:
  port: 19081

spring:
  application:
    name: service-datacenter
  datasource:

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8889/mysql?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    business:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:8889/mysql?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root

logging:
  path: ./DataCenterLog
  file: myLog.log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tianyi.datacenter.server.entity